training/quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"

urlpatterns = [
    path("home", views.quizhome, name="quiz_home"),
    path("choose_department", views.choose_department, name="choose_department"),
    path("scores", views.scores, name="scores"),
    path("<int:quiz_pk>/quiz_detail_landing", views.quiz_detail_landing, name="landing_page"),
    path("<int:quiz_pk>/quiz_detail/", views.quiz_detail, name="quiz_detail"),
    path("take_quiz/<int:quiz_pk>/<int:ques_no>", views.take_quiz, name="take quiz"),
]

training/training/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", RedirectView.as_view(url="/login/")),
    path('admin/', admin.site.urls),
    path("quiz/", include("quiz.urls")),
    path("documents/", include("documentcontrol.urls")),
    path("", include("user_login.urls")),
    path("", include("django.contrib.auth.urls")),  # bc of this django will automatically load the html under registration
    re_path(r'^_nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

training/quiz/models.py
from django.db import models
from django.contrib.auth.models import User


class Department(models.Model):
    """we will control who views what through this"""
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ManyToManyField(Department, related_name="employees")

    def __str__(self):
        return self.user.username

    def get_department(self):
        return self.department


# parent class that everything else will inherit from
class Quiz(models.Model):
    title = models.CharField(max_length=100, unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        """have to change this as we cannot have such a big string rep, here for debugging"""
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class UserAttempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    best_score = models.IntegerField(default=0)
    time_taken = models.IntegerField(default=0)  # this is to be able to add it to the table first
    date_taken = models.DateTimeField("Date Taken", null=True, auto_now_add=True)

    class Meta:
        unique_together = ('user', 'quiz')

    def __str__(self):
        score_value = str(self.score)
        return self.quiz.title + score_value

training/quiz/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question
from django.core.exceptions import ValidationError

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

    # def clean(self):
    #     cleaned_data = super().clean()
    #     answers = self.instance.answer_set.get.all()
    #     if answers.count() > 4:
    #         raise ValidationError
    #     return cleaned_data

training/quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Quiz, UserAttempt, Answer, Employee, Department, Question
from django.urls import reverse
from django.http import HttpResponse


@login_required(login_url="/login")
def quizhome(request):
    user = request.user
    try:
        department = user.employee.department.all()
        print(department)
    except Employee.DoesNotExist:
        return redirect(reverse("choose_department"))

    quiz = Quiz.objects.filter(department__in=department)
    # for q in quiz:
    #     print(q)
    return render(request, "quiz/home.html", {"quiz":quiz})


def choose_department(request):
    """In case department is not selected"""
    user = request.user
    if request.method == "POST":
        department_choice = Department.objects.get(id=request.POST.get("department"))
        # print(department_choice)
        employee, created = Employee.objects.get_or_create(user=user, department=department_choice)
        employee.save()
        return redirect(reverse("quiz_home"))
    else:
        return render(request, "quiz/choose_department.html", {"departments": Department.objects.all()})


@login_required(login_url="/login")
def quiz_detail(request, quiz_pk):
    if request.method == "POST":
        quiz = get_object_or_404(Quiz, pk=quiz_pk)
        user = request.user
        # TODO: time is not in the correct format
        time = int(request.POST.get('time_taken'))
        answer_ids = []
        
        attempt, created = UserAttempt.objects.get_or_create(user=user, quiz=quiz)
        if time < attempt.time_taken:
            attempt.time_taken = time

        # score has to be zero before we start calculating
        attempt.score = 0
        for ques in quiz.question_set.all():
            selected_answer = request.POST.get(f'selected_answers_{ques.id}')
            if selected_answer:  # to ensure that if a question is not answered we dont get an error 
                if Answer.objects.get(id=selected_answer).is_correct:
                    answer_ids.append(int(selected_answer))
                    attempt.score += 1
                    attempt.save()

        if attempt.score > attempt.best_score:
            attempt.best_score = attempt.score
            attempt.save()

        return render(request, "quiz/quiz_results.html", {"score":attempt.score,
                                                          "quiz":quiz,
                                                          "time_taken": attempt.time_taken,
                                                          "correct_answer":answer_ids}) 
    else:
        quiz = get_object_or_404(Quiz, pk=quiz_pk)
        return render(request, "quiz/quiz_detail.html", {"quiz": quiz})


@login_required(login_url="/login")
def quiz_detail_landing(request, quiz_pk):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    try:
        attempt = UserAttempt.objects.get(user=request.user, quiz=quiz)
        best_score = attempt.best_score
    except UserAttempt.DoesNotExist:
        best_score = 0

    return render(request, "quiz/quiz_landing_page.html", {"quiz":quiz, "best_score": best_score, "count": quiz.question_set.count()})


@login_required(login_url="/login")
def scores(request):
    user = request.user
    attempts = UserAttempt.objects.filter(user=user)
    print(attempts)
    return render(request, "quiz/scores.html", {"user_attempt":attempts})


@login_required(login_url="/login")
def take_quiz(request, quiz_pk, ques_no):
    user = request.user
    quiz = Quiz.objects.get(pk=quiz_pk)

    if not quiz.question_set.all():
        return HttpResponse("There are no questions in this quiz")

    question_set = [ques.id for ques in quiz.question_set.all()]
    question_no = ques_no + 1
    attempt, created = UserAttempt.objects.get_or_create(user=user, quiz=quiz)

    try:
        # context = quiz, question
        if request.method == "POST":
            answer_id = request.POST.get("selected")  # we get the id of the answer from here
            if Answer.objects.get(pk=answer_id).is_correct:
                attempt.score += 1
                print(attempt.score)
                attempt.save()

            question = Question.objects.get(pk=question_set[ques_no])
            return render(request, "quiz/take_quiz.html", {"quiz":quiz, "question":question, "ques_id":question_no})
        else:
            attempt.score = 0
            attempt.save()
            question = Question.objects.get(pk=question_set[ques_no])
            return render(request, "quiz/take_quiz.html", {"quiz":quiz, "question":question, "ques_id":question_no})
    except IndexError:
        if attempt.score > attempt.best_score:
            attempt.best_score = attempt.score
        attempts = UserAttempt.objects.filter(user=user)
        return render(request, "quiz/scores.html", {"user_attempt": attempts})

training/quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block title %}My site{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quiz:quiz_home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quiz:scores' %}"> Scores</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="departmentsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Departments
                        </a>
                        <!-- we have to add only the deparments that the user will have access to -->
                        <ul class="dropdown-menu" aria-labelledby="departmentsDropdown">
                            <!-- none of these have a valid URL-->
                                <li><a class="dropdown-item" href="{% url 'quiz:quality' %}">Quality</a></li>
                                <li><a class="dropdown-item" href="#">Human Resources</a></li>
                                <li><a class="dropdown-item" href="#">Manufacturing</a></li>
                                <li><a class="dropdown-item" href="#">IT</a></li>
                                <li><a class="dropdown-item" href="#">Marketing</a></li>
                                <li><a class="dropdown-item" href="#">Legal Documents</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <span class="navbar-text">Logged in as {{ user.username }} | </span>
                        <a class="nav-link" href="/logout">Logout</a>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="flex-wrap">
        <!-- Your existing code for the sidebar -->
        <div class="bg-dark">
            <a class="d-flex text-decoration-none align-items-center">
                <!-- Add content for the sidebar if needed -->
            </a>
        </div>

        <!--When we extend the html, we append this html file to include content in the line below. Specified with the use of blocks-->
        <div class="container"> {% block content %} {% endblock %} </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

training/quiz/templates/quiz/choose_department.html
{% extends 'quiz/base.html' %}
{%block title%} {{user.username}} Select department {%endblock%}
{% load crispy_forms_tags %}

{%block content%}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <label for="department">Department:</label>
        <select name="department" id="department" class="form-control">
            {% for department in departments %}
                <option value="{{ department.id }}"> {{ department }} </option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div> 
{% endblock %}

training/quiz/templates/quiz/home.html
{% extends "quiz/base.html" %}
{% block title %} Quiz Home Page {% endblock %}
{% block content %}
<h1 class="text-center"> Quiz home </h1>

<div class="container">
    <h3 class="text-center my-5">Choose a quiz</h3>
        <div class="row">
            {% for q in quiz %}
            <div class="col-lg-4 mb-4">
                <div class="card mx-2 my-2">
                    <img src="https://picsum.photos/300/200" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title text-center">{{q.title}}</h4>
                        <p class="card-text">Number of Questions - {{ q.question_set.count }}<br>Quiz time limit - 30:00 mins</p>
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col">
                                    <a class="btn btn-primary w-100" href="{% url 'quiz:take quiz' q.id 0 %}">Take Quiz!</a>
                                </div>
                                <div class="col">
                                    <a class="btn btn-secondary w-100" href="{{q.title}}/reading">Read it!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
</div>

{% endblock %}

training/quiz/templates/quiz/quiz_detail.html
{% extends "quiz/base.html" %}

{% block title %} {{ quiz.title }} {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    .form-check-input{
        outline: 2px solid black;
    }
</style>

<div class="bg-light border rounded text-dark text-center" id="timer" style="padding-top:55px;"> Time left: <span id="time">00:00</span> minutes </div>

<div class="container" style="padding-top: 55px;">
    <h1 class="text-center">{{ quiz.title }}</h1>

    <form id="quizform" method="post">
        <input type="hidden" name="time_taken" id="timeTaken" value="">
        {% csrf_token %}{{ form|crispy }}

        {% for ques in quiz.question_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <h5 class="card-title">{{ ques.text }}</h5>
                    
                    {% for answer in ques.answer_set.all %}
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="selected_answers_{{ques.id}}" value="{{ answer.id }}" id="answer{{ answer.id }}">
                            <label class="form-check-label" for="answer{{ answer.id }}">
                                {{ answer.text }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>

<script>
    var startTime = new Date().getTime();
    var duration =  30;
    var display = document.getElementById('time');
    var endTime = new Date(new Date().getTime() + duration * 60000);

    function updateTimeTaken(){
        var now = new Date().getTime();
        var timeTaken = Math.floor((now - startTime) / 1000);
        document.getElementById("timeTaken").value = timeTaken;
    }

    function startTimer() {
        var x = setInterval(function() {
            var now = new Date().getTime();
            var distance = endTime - now;

            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))
            var seconds = Math.floor((distance % (1000 * 60)) / (1000))

            display.innerHTML = minutes + "m " + seconds + "s ";

            if (distance < 0) {
                clearInterval(x);
                display.innerHTML = "EXPIRED";
                document.getElementById("quizform").submit()
            }
        }, 1000);
    }

    document.getElementById("quizform").addEventListener("submit", updateTimeTaken)

    window.onload = function() {
        startTimer();
    }

</script>

{% endblock %}

training/quiz/templates/quiz/quiz_landing_page.html
{% extends "quiz/base.html" %}

{% block title %} {{ quiz.title }} {% endblock %}

{% block content %}
<div class="container" style="padding-top: 55px;">
    <h1 class="text-center">{{quiz.title}}</h1>
    <h2> Time Limit: 30 <br> Number of Questions: {{count}} <br> Best Score: {{best_score}}</h2>
    <div class="text-center">
        <a class="btn btn-primary w-25" href="{% url 'quiz:quiz_detail' quiz.id %}">Start</a>
    </div>
</div>
{% endblock %}

training/quiz/templates/quiz/quiz_results.html
{% extends "quiz/base.html" %}
{% block title %} Quiz {{quiz.title}} Results {%endblock%}
<!-- objects passed -> attempt, quiz-->
{%block content%}
<h1 class="text-center" style="padding-top: 55px;">Your score is {{score}}</h1>
<h2 class="text-center"> Time - {{time_taken}} </h2>

{% for ques in quiz.question_set.all %}
    <fieldset class="border">
        <legend> Question: {{ques}} </legend>
            {% for answer in ques.answer_set.all %}
                <label>
                    {% if answer.id in correct_answer %}
                    <strong style="color: green;">Correctly answered-> {{answer.text}}</strong><br>
                    {% else %}
                    {{ answer.text }} | {{answer.is_correct}}
                </label><br>
                {% endif %}
        {%endfor%}
    </fieldset>
{%endfor%} 
{%endblock%}

training/quiz/templates/quiz/scores.html
{%extends "quiz/base.html" %}
{%block title%} Scores {{user.username}} {%endblock%}

{%block content%}
<div class="container" style="padding-top: 55px;">
    <h1 class="text-center"> All your scores {{user.username}} </h1>
    <div class="container col-md-6">
        {% for attempt in user_attempt%}
        <ol class="list-group">
            <li class="list-group-item text-center">
                {{attempt.quiz}} : {{attempt.score}}
            </li>
        </ol> 
        {%endfor%}
    </div>
</div>

{%endblock%}

training/quiz/templates/quiz/take_quiz.html
{% extends "quiz/base.html" %}

{% block title %} {{ quiz.title }} {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    .form-check-input{
        outline: 2px solid black;
    }
</style>

<h1 class="text-center" style="padding-top:55px;"> {{quiz.title}} </h1>

<div class="container d-flex justify-content-center align-items-center" style="padding-top: 55px;">
    <form id="quizform" method="post" action="{% url "quiz:take quiz" quiz.id ques_id %}">
        {% csrf_token %} {{ form|crispy }}

        <div class="card" style="height: 300px; width: 300px;">
            <div class="card-body d-flex flex-column align-items-center">
                <h4 class="card-title"> {{ question.text }} </h4>
                    {% for answer in question.answer_set.all %}
                    <div class="form-check text-center mx-3 my-3 w-100 h-100">
                        <input class="form-check-input" type="radio" name="selected" value="{{ answer.id }}" id="answer_{{answer.id}}">
                        <label class="form-check-label" for="answer_{{answer.id}}"> 
                            {{answer.text}}
                        </label>
                    </div>
                    {% endfor %}
            </div>
        </div>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>

{% endblock %}